#!/bin/bash

	 key1 = str(input("Key : "))
	 Value1 = str(input("Value : "))
	 key2 = str(input("Key : "))
	 Value2 = str(input("Value : "))
	 key3 = str(input("Key : "))
	 Value3 = str(input("Value : "))
	 key4 = str(input("Key : "))
	 Value4 = str(input("Value : "))
	 key5 = str(input("Key : "))
	 Value5 = str(input("Value : "))
	 key6 = str(input("Key : "))
	 Value6 = str(input("Value : "))
	 key7 = str(input("Key : "))
	 Value7 = str(input("Value : "))
	 key8 = str(input("Key : "))
	 Value8 = str(input("Value : "))
	 key9 = str(input("Key : "))
	 Value9 = str(input("Value : "))
	 key10 = str(input("Key : "))
	 Value10 = str(input("Value : "))
	 key11 = str(input("Key : "))
	 Value11 = str(input("Value : "))
	 key12 = str(input("Key : "))
	 Value12 = str(input("Value : "))